CREATE DATABASE TrainingDB;
GO

USE TrainingDB;
GO

CREATE TABLE EMPLOYEE (
    EmployeeID INT PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    JobTitle VARCHAR(50),
    Email VARCHAR(100),
    Address VARCHAR(200),
    PhoneNumber VARCHAR(15),
    SubjectTaught VARCHAR(100), 
    Specialization VARCHAR(100) 
);

CREATE TABLE DEPARTMENT (
    DepartmentID INT PRIMARY KEY,
    DepartmentName VARCHAR(50) NOT NULL,
    DepartmentAddress VARCHAR(200)
);

CREATE TABLE EMPLOYEE_DEPARTMENT (
    EmployeeDepartmentID INT PRIMARY KEY,
    EmployeeID INT NOT NULL FOREIGN KEY REFERENCES EMPLOYEE(EmployeeID),
    DepartmentID INT NOT NULL FOREIGN KEY REFERENCES DEPARTMENT(DepartmentID),
    StartDate DATE NOT NULL,
    EndDate DATE,
    Salary DECIMAL(10, 2)
);

CREATE TABLE COURSE (
    CourseID INT PRIMARY KEY IDENTITY,
    Title VARCHAR(100) NOT NULL,
    TotalHours INT NOT NULL,
    Description VARCHAR(500)
);

CREATE TABLE PREREQUISITE_COURSE (
    PrerequisiteID INT PRIMARY KEY,
    CourseID INT NOT NULL FOREIGN KEY REFERENCES COURSE(CourseID),
    PrerequisiteCourseID INT NOT NULL FOREIGN KEY REFERENCES COURSE(CourseID)
);

CREATE TABLE OFFERING (
    OfferingID INT PRIMARY KEY,
    CourseID INT NOT NULL FOREIGN KEY REFERENCES COURSE(CourseID),
    Name VARCHAR(100) NOT NULL,
    Type VARCHAR(20) CHECK (Type IN ('Mandatory', 'Optional')),
    Hours INT NOT NULL,
    TeacherID INT NOT NULL FOREIGN KEY REFERENCES EMPLOYEE(EmployeeID)
);

ALTER TABLE OFFERING
ADD CONSTRAINT Unique_Offering_Teacher UNIQUE (OfferingID, TeacherID);

CREATE TABLE EMPLOYEE_TRAINEE (
    TraineeID INT PRIMARY KEY IDENTITY,
    EmployeeID INT NOT NULL FOREIGN KEY REFERENCES EMPLOYEE(EmployeeID),
    CourseID INT NOT NULL FOREIGN KEY REFERENCES COURSE(CourseID),
    FinalGrade DECIMAL(5, 2)
);

CREATE TABLE TRAINEE_OFFERING_GRADE (
    TraineeOfferingGradeID INT PRIMARY KEY IDENTITY,
    TraineeID INT NOT NULL FOREIGN KEY REFERENCES EMPLOYEE_TRAINEE(TraineeID),
    OfferingID INT NOT NULL FOREIGN KEY REFERENCES OFFERING(OfferingID),
    Grade DECIMAL(5, 2)
);
